In [1]:
from sklearnex import patch_sklearn
patch_sklearn()

Intel(R) Extension for Scikit-learn* enabled (https://github.com/intel/scikit-learn-intelex)


In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 

from sklearn.utils import shuffle
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import cross_val_score, GridSearchCV, train_test_split, StratifiedKFold, cross_validate
from sklearn.preprocessing import LabelEncoder, StandardScaler

# Loading of the data

Start by loading the data of the metadata and the two extracted features sets

In [2]:
metadata = pd.read_csv("processed_metadata.csv")
metadata.head()

path  segment  mod      label  \
0  ./Labelled/Bleatings/evt_000_000_000681_210415...        0    0  Bleatings   
1  ./Labelled/Bleatings/evt_000_000_000681_210415...        1    0  Bleatings   
2  ./Labelled/Bleatings/evt_000_000_000681_210415...        2    0  Bleatings   
3  ./Labelled/Bleatings/evt_000_000_000681_210415...        3    0  Bleatings   
4  ./Labelled/Bleatings/evt_000_000_000682_210415...        0    0  Bleatings   

   samplingrate      ms  
0         16000  3000.0  
1         16000  3000.0  
2         16000  3000.0  
3         16000  3000.0  
4         16000  3000.0

In [3]:
d1 = pd.read_csv("mfcc_deltamfcc_stat.csv", index_col = 'Unnamed: 0')
np.shape(d1)

(7005, 130)

In [4]:
d2 = pd.read_csv("mfcc_deltamfcc_entire.csv", index_col = 'Unnamed: 0')
np.shape(d2)

(7005, 2444)

Preapare the data for SVC model by extracting the labels and scaling the features sets

In [5]:
# Transforming non numerical labels into numerical labels
labels = metadata["label"]
encoder = LabelEncoder()

# encoding train labels
y = encoder.fit_transform(labels)

In [6]:
# scale the features
scaler = StandardScaler()

x1 = scaler.fit_transform(d1)
x2 = scaler.fit_transform(d2)

# 10-fold Cross Validation

Start evaluating the two features set using a SVC model setup with a rbf kernel and C=1 using 10 fold cv. The choosen metrics are accuracy and auroc

In [7]:
# set up cross validation procedure
scoring = {'acc': 'accuracy',
           'auroc': 'roc_auc_ovr'}

kfold = StratifiedKFold(n_splits=10, shuffle=True, random_state=10)

In [21]:
scores1 = cross_validate(SVC(probability=True), x1, y, cv=kfold.split(x1, y), scoring=scoring, return_train_score=True)

In [22]:
scores1

{'fit_time': array([10.80603361, 10.51901817,  9.85302067, 10.19201636, 10.56499696,
        10.6590147 , 11.3940773 , 10.99008584, 11.29201531, 10.47199607]),
 'score_time': array([0.8359983 , 0.77302909, 0.74999976, 0.75597429, 0.76199603,
        0.80299783, 0.77198195, 0.75700474, 0.76600003, 0.75900388]),
 'test_acc': array([0.87731812, 0.87874465, 0.88159772, 0.88445078, 0.84450785,
        0.85142857, 0.85428571, 0.87285714, 0.87571429, 0.86571429]),
 'train_acc': array([0.92020939, 0.92227157, 0.92052665, 0.91989213, 0.92258883,
        0.92164948, 0.92275971, 0.92307692, 0.9222839 , 0.92323553]),
 'test_auroc': array([0.97001498, 0.96945703, 0.96995034, 0.96686378, 0.95749278,
        0.95691416, 0.95979439, 0.96466107, 0.96714022, 0.95808698]),
 'train_auroc': array([0.98459744, 0.98418174, 0.98449947, 0.98467511, 0.98508035,
        0.98527764, 0.98507997, 0.98483238, 0.98476402, 0.98492226])}

In [37]:
scores2 = cross_validate(SVC(probability=True), x2, y, cv=kfold.split(x2, y), scoring=scoring, return_train_score=True)

C:\Users\Nicolas Facchinetti\.conda\envs\progapr\lib\site-packages\sklearn\model_selection\_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\Nicolas Facchinetti\.conda\envs\progapr\lib\site-packages\sklearn\model_selection\_validation.py", line 762, in _score
    scores = scorer(estimator, X_test, y_test)
  File "C:\Users\Nicolas Facchinetti\.conda\envs\progapr\lib\site-packages\sklearn\metrics\_scorer.py", line 103, in __call__
    score = scorer._score(cached_call, estimator, *args, **kwargs)
  File "C:\Users\Nicolas Facchinetti\.conda\envs\progapr\lib\site-packages\sklearn\metrics\_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Nicolas Facchinetti\.conda\envs\progapr\lib\site-packages\sklearn\metrics\_scorer.py", line 68, in _cached_call
    return getattr(estimator, method)(*args, **kwargs)

C:\Users\Nicolas Facchinetti\.conda\envs\progapr\lib\site-packages\sklearn\model_selection\_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\Nicolas Facchinetti\.conda\envs\progapr\lib\site-packages\sklearn\model_selection\_validation.py", line 762, in _score
    scores = scorer(estimator, X_test, y_test)
  File "C:\Users\Nicolas Facchinetti\.conda\envs\progapr\lib\site-packages\sklearn\metrics\_scorer.py", line 103, in __call__
    score = scorer._score(cached_call, estimator, *args, **kwargs)
  File "C:\Users\Nicolas Facchinetti\.conda\envs\progapr\lib\site-packages\sklearn\metrics\_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Nicolas Facchinetti\.conda\envs\progapr\lib\site-packages\sklearn\metrics\_scorer.py", line 68, in _cached_call
    return getattr(estimator, method)(*args, **kwargs)

C:\Users\Nicolas Facchinetti\.conda\envs\progapr\lib\site-packages\sklearn\model_selection\_validation.py:771: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\Nicolas Facchinetti\.conda\envs\progapr\lib\site-packages\sklearn\model_selection\_validation.py", line 762, in _score
    scores = scorer(estimator, X_test, y_test)
  File "C:\Users\Nicolas Facchinetti\.conda\envs\progapr\lib\site-packages\sklearn\metrics\_scorer.py", line 103, in __call__
    score = scorer._score(cached_call, estimator, *args, **kwargs)
  File "C:\Users\Nicolas Facchinetti\.conda\envs\progapr\lib\site-packages\sklearn\metrics\_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Nicolas Facchinetti\.conda\envs\progapr\lib\site-packages\sklearn\metrics\_scorer.py", line 68, in _cached_call
    return getattr(estimator, method)(*args, **kwargs)

KeyboardInterrupt: 

In [ ]:
scores2

# Old

In [32]:
# get train and test data
# X1_train, X1_test, y1_train, y1_test = train_test_split(x, y, test_size=0.2)

In [33]:
m = SVC()

In [ ]:
m.fit(X1_train, y1_train)

In [21]:
Y_pred = m.predict(X1_test)

In [22]:
Y_pred

array([0, 2, 0, ..., 2, 2, 1])

In [23]:
list(encoder.inverse_transform(Y_pred1))

['Bleatings',
 'Others',
 'Bleatings',
 'Others',
 'Others',
 'Bleatings',
 'ContactCalls',
 'Bleatings',
 'Others',
 'Others',
 'Others',
 'ContactCalls',
 'Bleatings',
 'ContactCalls',
 'Others',
 'Bleatings',
 'ContactCalls',
 'Bleatings',
 'Others',
 'ContactCalls',
 'Bleatings',
 'Others',
 'ContactCalls',
 'Others',
 'Bleatings',
 'Bleatings',
 'Others',
 'Bleatings',
 'Bleatings',
 'ContactCalls',
 'Bleatings',
 'Bleatings',
 'Others',
 'Others',
 'ContactCalls',
 'ContactCalls',
 'Others',
 'Bleatings',
 'Others',
 'Others',
 'Others',
 'Others',
 'Bleatings',
 'ContactCalls',
 'ContactCalls',
 'Others',
 'Bleatings',
 'ContactCalls',
 'ContactCalls',
 'Others',
 'Others',
 'ContactCalls',
 'ContactCalls',
 'ContactCalls',
 'ContactCalls',
 'ContactCalls',
 'Others',
 'ContactCalls',
 'Bleatings',
 'Others',
 'ContactCalls',
 'Others',
 'Bleatings',
 'ContactCalls',
 'Others',
 'Others',
 'Others',
 'ContactCalls',
 'Others',
 'ContactCalls',
 'Bleatings',
 'ContactCalls',
 'Ot

# Base classifier

In [26]:
print(confusion_matrix(y1_test,Y_pred1))
print("\n")
print(classification_report(y1_test,Y_pred1))

print("Training set score for SVM: %f" % m1.score(X1_train , y1_train))
print("Testing  set score for SVM: %f" % m1.score(X1_test  , y1_test ))

m1.score

[[332 138  11]
 [ 71 344   6]
 [ 11   6 482]]


              precision    recall  f1-score   support

           0       0.80      0.69      0.74       481
           1       0.70      0.82      0.76       421
           2       0.97      0.97      0.97       499

    accuracy                           0.83      1401
   macro avg       0.82      0.82      0.82      1401
weighted avg       0.83      0.83      0.83      1401

Training set score for SVM: 0.956817
Testing  set score for SVM: 0.826552


<bound method ClassifierMixin.score of SVC()>

In [27]:
m1.score

<bound method ClassifierMixin.score of SVC()>

In [25]:
print(confusion_matrix(y2_test,Y_pred2))
print("\n")
print(classification_report(y2_test,Y_pred2))

print("Training set score for SVM: %f" % m2.score(X2_train , y2_train))
print("Testing  set score for SVM: %f" % m2.score(X2_test  , y2_test ))

m2.score

[[386  81  12]
 [ 77 361   6]
 [  5   0 473]]


              precision    recall  f1-score   support

           0       0.82      0.81      0.82       479
           1       0.82      0.81      0.81       444
           2       0.96      0.99      0.98       478

    accuracy                           0.87      1401
   macro avg       0.87      0.87      0.87      1401
weighted avg       0.87      0.87      0.87      1401

Training set score for SVM: 0.918630
Testing  set score for SVM: 0.870807


<bound method ClassifierMixin.score of SVC()>

# Grid Search

In [34]:
params_grid = [{'kernel': ['rbf'],'C': [0.1, 1, 10, 100, 1000]},
               {'kernel': ['linear'], 'C': [0.1, 1, 10, 100, 1000]}]

In [35]:
svm_model = GridSearchCV(SVC(), params_grid, cv=5)
svm_model.fit(X1_train, y1_train)

KeyboardInterrupt: 

In [ ]:
# View the accuracy score
print('Best score for training data:', svm_model.best_score_,"\n") 

# View the best parameters for the model found using grid search
print('Best C:',svm_model.best_estimator_.C,"\n") 
print('Best Kernel:',svm_model.best_estimator_.kernel,"\n")
print('Best Gamma:',svm_model.best_estimator_.gamma,"\n")

final_model = svm_model.best_estimator_
Y_pred = final_model.predict(X1_test)
Y_pred_label = list(encoder.inverse_transform(Y_pred))

In [ ]:
print(confusion_matrix(y1_test,Y_pred))
print("\n")
print(classification_report(y1_test,Y_pred))

print("Training set score for SVM: %f" % final_model.score(X1_train, y1_train))
print("Testing  set score for SVM: %f" % final_model.score(X1_test, y1_test ))

svm_model.score

In [ ]:
svm_model2 = GridSearchCV(SVC(), params_grid, cv=5)
svm_model2.fit(X2_train, y2_train)

In [ ]:
# View the accuracy score
print('Best score for training data:', svm_model2.best_score_,"\n") 

# View the best parameters for the model found using grid search
print('Best C:',svm_model2.best_estimator_.C,"\n") 
print('Best Kernel:',svm_model2.best_estimator_.kernel,"\n")
print('Best Gamma:',svm_model2.best_estimator_.gamma,"\n")

final_model = svm_model2.best_estimator_
Y_pred = final_model.predict(X2_test)
Y_pred_label = list(encoder.inverse_transform(Y_pred))

In [ ]:
print(confusion_matrix(y2_test,Y_pred))
print("\n")
print(classification_report(y2_test,Y_pred))

print("Training set score for SVM: %f" % final_model.score(X2_train, y2_train))
print("Testing  set score for SVM: %f" % final_model.score(X2_test, y2_test ))

svm_model.score