In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 

from sklearn.utils import shuffle
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import cross_val_score, GridSearchCV, train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [3]:
metadata = pd.read_csv("processed_metadata.csv")
d1 = pd.read_csv("mfcc_deltamfcc_entire.csv")
d2 = pd.read_csv("mfcc_deltamfcc_stat.csv")

In [5]:
metadata.head()

path  segment      label  \
0  ./Labelled/Bleatings/evt_000_000_000681_210415...        0  Bleatings   
1  ./Labelled/Bleatings/evt_000_000_000681_210415...        1  Bleatings   
2  ./Labelled/Bleatings/evt_000_000_000681_210415...        2  Bleatings   
3  ./Labelled/Bleatings/evt_000_000_000681_210415...        3  Bleatings   
4  ./Labelled/Bleatings/evt_000_000_000681_210415...        4  Bleatings   

   samplingrate      ms  
0         16000  3000.0  
1         16000  3000.0  
2         16000  3000.0  
3         16000  3000.0  
4         16000  3000.0

In [6]:
# Transforming non numerical labels into numerical labels
labels = metadata["label"]
encoder = LabelEncoder()

# encoding train labels
y = encoder.fit_transform(labels)

In [10]:
# scale the features
scaler = StandardScaler()
x1 = scaler.fit_transform(d1)
x2 = scaler.fit_transform(d2)

In [12]:
# get train and test data
X1_train, X1_test, y1_train, y1_test = train_test_split(x1, y, test_size=0.2)
X2_train, X2_test, y2_train, y2_test = train_test_split(x2, y, test_size=0.2)

In [13]:
m1 = SVC()
m2 = SVC()
m1.fit(X1_train, y1_train)
m2.fit(X2_train, y2_train)

SVC()

In [14]:
Y_pred1 = m1.predict(X1_test)
Y_pred2 = m2.predict(X2_test)

In [15]:
Y_pred1

array([1, 1, 2, ..., 2, 0, 2])

In [16]:
list(encoder.inverse_transform(Y_pred1))

['ContactCalls',
 'ContactCalls',
 'Others',
 'Bleatings',
 'Bleatings',
 'Others',
 'Others',
 'ContactCalls',
 'Others',
 'Others',
 'Bleatings',
 'ContactCalls',
 'Others',
 'Bleatings',
 'ContactCalls',
 'Others',
 'Bleatings',
 'Others',
 'Others',
 'Bleatings',
 'Bleatings',
 'Bleatings',
 'Bleatings',
 'Others',
 'ContactCalls',
 'Others',
 'Bleatings',
 'Bleatings',
 'Others',
 'Bleatings',
 'ContactCalls',
 'Others',
 'Bleatings',
 'ContactCalls',
 'Bleatings',
 'Bleatings',
 'Others',
 'Bleatings',
 'Others',
 'Others',
 'Bleatings',
 'Bleatings',
 'Others',
 'Bleatings',
 'Bleatings',
 'Others',
 'Bleatings',
 'Others',
 'Others',
 'Others',
 'Others',
 'Bleatings',
 'Others',
 'Others',
 'ContactCalls',
 'Bleatings',
 'Bleatings',
 'Others',
 'Bleatings',
 'Bleatings',
 'ContactCalls',
 'Others',
 'Bleatings',
 'Bleatings',
 'Bleatings',
 'ContactCalls',
 'Others',
 'Bleatings',
 'ContactCalls',
 'ContactCalls',
 'Others',
 'Bleatings',
 'Others',
 'Bleatings',
 'Others',
 

In [19]:
print(confusion_matrix(y1_test,Y_pred1))
print("\n")
print(classification_report(y1_test,Y_pred1))

print("Training set score for SVM: %f" % m1.score(X1_train , y1_train))
print("Testing  set score for SVM: %f" % m1.score(X1_test  , y1_test ))

m1.score

[[541  15   0]
 [ 40 161   0]
 [  0   0 571]]


              precision    recall  f1-score   support

           0       0.93      0.97      0.95       556
           1       0.91      0.80      0.85       201
           2       1.00      1.00      1.00       571

    accuracy                           0.96      1328
   macro avg       0.95      0.92      0.94      1328
weighted avg       0.96      0.96      0.96      1328

Training set score for SVM: 0.990586
Testing  set score for SVM: 0.958584


<bound method ClassifierMixin.score of SVC()>

In [20]:
print(confusion_matrix(y2_test,Y_pred2))
print("\n")
print(classification_report(y2_test,Y_pred2))

print("Training set score for SVM: %f" % m2.score(X2_train , y2_train))
print("Testing  set score for SVM: %f" % m2.score(X2_test  , y2_test ))

m2.score

[[540  15   6]
 [139  75   3]
 [  4   0 546]]


              precision    recall  f1-score   support

           0       0.79      0.96      0.87       561
           1       0.83      0.35      0.49       217
           2       0.98      0.99      0.99       550

    accuracy                           0.87      1328
   macro avg       0.87      0.77      0.78      1328
weighted avg       0.88      0.87      0.86      1328

Training set score for SVM: 0.982113
Testing  set score for SVM: 0.874247


<bound method ClassifierMixin.score of SVC()>